export enum PerceptionsModalTypes {
    OPEN_PERCEPTIONS_MODAL = '[auth] OPEN_PERCEPTIONS_MODAL',
    CLOSE_PERCEPTIONS_MODAL = '[auth] CLOSE_PERCEPTIONS_MODAL',
    REACTIVE_PERCEPTIONS_COL = '[auth] REACTIVE_PERCEPTIONS_COL'
}