export enum NonWorkingDayTypes {
    OPEN_NONWORKINGDAY_MODAL = '[auth] OPEN_NONWORKINGDAY_MODAL',
    CLOSE_NONWORKINGDAY_MODAL = '[auth] CLOSE_NONWORKINGDAY_MODAL',
    REACTIVE_NONWORKINGDAY_COL = '[auth] REACTIVE_NONWORKINGDAY_COL',
    UPDATE_NONWORKINGDAYS ='[auth] UPDATE_NONWORKINGDAYS',
}